[package]
name = "blockspeed"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
eyre.workspace = true

eth-kit-metrics.workspace = true
blockspeed-cmd.workspace = true
blockspeed-echo.workspace = true
blockspeed-trace.workspace = true

[features]
default = []

[[bin]]
name = "blockspeed"
path = "src/main.rs"