{
 "title": "Blockspeed",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Mgas/s - Over Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"blockspeed\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"blockspeed_mgas\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\n  |> group(columns: [\"uri\"])"
    }
   ]
  },
  {
   "title": "TPS - Over Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"blockspeed\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"blockspeed_tps\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"uri\"])\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\n  |> fill(value: 0.0)"
    }
   ]
  },
  {
   "title": "Gas Used  - Over Time (Million)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"blockspeed\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"blockspeed_gas_used\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"uri\"])\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\n  |> map(fn: (r) => ({ r with _value: r._value / 1000000.0 }))\n  |> fill(value: 0.0)"
    }
   ]
  },
  {
   "title": "Mined Txs - Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"blockspeed\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"blockspeed_txs\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"uri\"])\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\n  |> map(fn: (r) => ({ r with _value: r._value }))\n  |> fill(value: 0.0)"
    }
   ]
  },
  {
   "title": "Num of Blocks per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"blockspeed\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"blockspeed_block_per_sec\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"uri\"])\n  |> aggregateWindow(\n      every: v.windowPeriod,\n      fn: sum,\n      createEmpty: false\n    )\n  |> fill(value: 0.0)\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])"
    }
   ]
  }
 ]
}